### ISSUE TITLE
[Auth] Auth page says DocBase

### ISSUE THREAD

**Issue by alanagoyal** [alanagoyal/rebase#15]
<img width="495" alt="CleanShot 2023-08-26 at 08 35 36@2x" src="https://github.com/alanagoyal/rebase/assets/17993385/4a075275-92ad-4a35-a03d-1148bb3e9524">

**Comment by mathurah** [comment]
I can't find anything in the code to change the settings for this, it might be how your supabase oauth is set up? Are you using the same google client app id as the docbase project? @alanagoyal

**Comment by alanagoyal** [comment]
ah probably in the oauth setup in google console

Sent via Superhuman iOS ( ***@***.*** )

**Comment by alanagoyal** [comment]
fixed!
