### ISSUE TITLE
[Email Drafting] Unable to send email - to highlighted red

### ISSUE THREAD

**Issue by mathurah** [alanagoyal/rebase#7]
<img width="594" alt="image" src="https://github.com/alanagoyal/rebase/assets/31157307/a47cc288-77d0-42ae-9312-48f64a780bee">

**Comment by alanagoyal** [comment]
fyi i think this is related to the zod types in the shadcn form. at least when i've seen this red in forms before, that's what it is. i haven't looked too closely at the code, but i wonder if it's because it's not an "email" anymore.

**Comment by mathurah** [comment]
> 

yeah I fixed it! I think the error came up because I was using the `CreatableSelect` component to allow the multi-select drop down, which stored the emails in a different format
